// 10 built-in visual designs for the Business Card feature, modeled after
// common premium visiting-card layouts (framed border, top band, split
// block, corner accent, minimal). `layout` picks which structure
// BusinessCardPreview renders; the rest are per-template colors. Keep `id`
// values in sync with business-card.validation.js on the backend
// (CARD_TEMPLATES).
export const CARD_TEMPLATES = [
  {
    id: 'navy',
    label: 'Midnight Gold',
    layout: 'framed',
    gradient: ['#0B0B0F', '#1A1A1F'],
    text: '#FFFFFF',
    muted: '#9CA3AF',
    accent: '#D4AF37',
  },
  {
    id: 'minimal',
    label: 'Rose Gold Frame',
    layout: 'framed',
    gradient: ['#F5D0C5', '#E8B4A8'],
    text: '#5C3A3A',
    muted: '#8B6A63',
    accent: '#8B5E52',
  },
  {
    id: 'ocean',
    label: 'Gold Foil Band',
    layout: 'band',
    gradient: ['#D4AF37', '#B8860B'],
    text: '#2A1F00',
    muted: '#5C4A16',
    accent: '#1A1A1F',
    blockColor: '#1A1A1F',
    blockText: '#D4AF37',
  },
  {
    id: 'sunset',
    label: 'Navy & Gold Band',
    layout: 'band',
    gradient: ['#0F172A', '#1E293B'],
    text: '#FFFFFF',
    muted: '#94A3B8',
    accent: '#D4AF37',
    blockColor: '#D4AF37',
    blockText: '#1A1A1F',
  },
  {
    id: 'emerald',
    label: 'Sandstone Split',
    layout: 'split',
    gradient: ['#F5F0E6', '#F5F0E6'],
    text: '#0B3D2E',
    muted: '#3F6657',
    accent: '#0B3D2E',
    blockColor: '#0B3D2E',
    blockText: '#F5F0E6',
  },
  {
    id: 'royal',
    label: 'Deep Teal Split',
    layout: 'split',
    gradient: ['#0F3D3E', '#0F3D3E'],
    text: '#F1F5F4',
    muted: '#B9D3D0',
    accent: '#F1F5F4',
    blockColor: '#F1F5F4',
    blockText: '#0F3D3E',
  },
  {
    id: 'charcoal',
    label: 'Noir Minimal',
    layout: 'minimal',
    gradient: ['#000000', '#000000'],
    text: '#FFFFFF',
    muted: '#9CA3AF',
    accent: '#D4AF37',
  },
  {
    id: 'coral',
    label: 'Brushed Silver',
    layout: 'minimal',
    gradient: ['#E5E7EB', '#CBD5E1'],
    text: '#1F2130',
    muted: '#64748B',
    accent: '#475569',
  },
  {
    id: 'slate',
    label: 'Ivory Corner Teal',
    layout: 'corner',
    gradient: ['#FDFBF7', '#FDFBF7'],
    text: '#1F2130',
    muted: '#64748B',
    accent: '#F5A524',
    blockColor: '#0F6B5C',
  },
  {
    id: 'rosegold',
    label: 'Coral Corner',
    layout: 'corner',
    gradient: ['#FFFFFF', '#FFFFFF'],
    text: '#1F2130',
    muted: '#64748B',
    accent: '#F43F5E',
    blockColor: '#F43F5E',
  },

  // --- 20 more ---
  {
    id: 'crimson',
    label: 'Crimson Ribbon',
    layout: 'ribbon',
    gradient: ['#7F1D1D', '#450A0A'],
    text: '#FFFFFF',
    muted: '#FCA5A5',
    accent: '#D4AF37',
    blockColor: '#D4AF37',
    blockText: '#450A0A',
  },
  {
    id: 'sapphire',
    label: 'Sapphire Circle',
    layout: 'circle',
    gradient: ['#1E3A8A', '#1E40AF'],
    text: '#FFFFFF',
    muted: '#BFDBFE',
    accent: '#FFFFFF',
    blockColor: 'rgba(255,255,255,0.16)',
  },
  {
    id: 'mint',
    label: 'Mint Fresh',
    layout: 'dual',
    gradient: ['#A7F3D0', '#A7F3D0'],
    text: '#065F46',
    muted: '#0F766E',
    accent: '#065F46',
    blockColor: '#065F46',
    blockText: '#ECFDF5',
  },
  {
    id: 'graphite',
    label: 'Graphite Stack',
    layout: 'stacked',
    gradient: ['#374151', '#1F2937'],
    text: '#F9FAFB',
    muted: '#9CA3AF',
    accent: '#D1D5DB',
  },
  {
    id: 'peach',
    label: 'Peach Blossom',
    layout: 'bottomBand',
    gradient: ['#FFD9C0', '#FFB199'],
    text: '#7C2D12',
    muted: '#9A3412',
    accent: '#7C2D12',
    blockColor: '#7C2D12',
    blockText: '#FFE4D6',
  },
  {
    id: 'indigo',
    label: 'Indigo Diagonal',
    layout: 'diagonal',
    gradient: ['#312E81', '#1E1B4B'],
    text: '#FFFFFF',
    muted: '#C7D2FE',
    accent: '#FDE68A',
    blockColor: '#7C3AED',
  },
  {
    id: 'lagoon',
    label: 'Lagoon Circle',
    layout: 'circle',
    gradient: ['#06B6D4', '#0E7490'],
    text: '#FFFFFF',
    muted: '#CFFAFE',
    accent: '#FFFFFF',
    blockColor: 'rgba(255,255,255,0.18)',
  },
  {
    id: 'amber',
    label: 'Amber Ribbon',
    layout: 'ribbon',
    gradient: ['#D97706', '#92400E'],
    text: '#FFFFFF',
    muted: '#FDE7C8',
    accent: '#1A1A1F',
    blockColor: '#1A1A1F',
    blockText: '#FDE68A',
  },
  {
    id: 'orchid',
    label: 'Orchid Dual',
    layout: 'dual',
    gradient: ['#F3E8FF', '#F3E8FF'],
    text: '#6B21A8',
    muted: '#7E22CE',
    accent: '#6B21A8',
    blockColor: '#C026D3',
    blockText: '#FDF4FF',
  },
  {
    id: 'forest',
    label: 'Forest Stack',
    layout: 'stacked',
    gradient: ['#14532D', '#166534'],
    text: '#F0FDF4',
    muted: '#BBF7D0',
    accent: '#FDE68A',
  },
  {
    id: 'blush',
    label: 'Blush Band',
    layout: 'bottomBand',
    gradient: ['#FBCFE8', '#F9A8D4'],
    text: '#831843',
    muted: '#9D174D',
    accent: '#831843',
    blockColor: '#831843',
    blockText: '#FCE7F3',
  },
  {
    id: 'steel',
    label: 'Steel Diagonal',
    layout: 'diagonal',
    gradient: ['#CBD5E1', '#94A3B8'],
    text: '#1E293B',
    muted: '#334155',
    accent: '#0F172A',
    blockColor: '#475569',
  },
  {
    id: 'cocoa',
    label: 'Cocoa Minimal',
    layout: 'minimal',
    gradient: ['#4E342E', '#3E2723'],
    text: '#EFEBE9',
    muted: '#BCAAA4',
    accent: '#D7CCC8',
  },
  {
    id: 'citrus',
    label: 'Citrus Corner',
    layout: 'corner',
    gradient: ['#FEF9C3', '#FEF08A'],
    text: '#713F12',
    muted: '#854D0E',
    accent: '#EA580C',
    blockColor: '#EA580C',
  },
  {
    id: 'plum',
    label: 'Plum Frame',
    layout: 'framed',
    gradient: ['#581C46', '#831843'],
    text: '#FFFFFF',
    muted: '#F0ABFC',
    accent: '#D4AF37',
  },
  {
    id: 'arctic',
    label: 'Arctic Split',
    layout: 'split',
    gradient: ['#E0F2FE', '#E0F2FE'],
    text: '#0C4A6E',
    muted: '#0369A1',
    accent: '#0C4A6E',
    blockColor: '#0C4A6E',
    blockText: '#E0F2FE',
  },
  {
    id: 'ember',
    label: 'Ember Ribbon',
    layout: 'ribbon',
    gradient: ['#1A1A1A', '#7F1D1D'],
    text: '#FFFFFF',
    muted: '#FCA5A5',
    accent: '#FB923C',
    blockColor: '#FB923C',
    blockText: '#1A1A1A',
  },
  {
    id: 'sage',
    label: 'Sage Circle',
    layout: 'circle',
    gradient: ['#84A98C', '#52796F'],
    text: '#FFFFFF',
    muted: '#D8E2DC',
    accent: '#FFFFFF',
    blockColor: 'rgba(255,255,255,0.2)',
  },
  {
    id: 'cobalt',
    label: 'Cobalt Band',
    layout: 'band',
    gradient: ['#1D4ED8', '#1E3A8A'],
    text: '#FFFFFF',
    muted: '#BFDBFE',
    accent: '#FFFFFF',
    blockColor: '#FFFFFF',
    blockText: '#1D4ED8',
  },
  {
    id: 'champagne',
    label: 'Champagne Stack',
    layout: 'stacked',
    gradient: ['#EFE3C8', '#D9C89E'],
    text: '#5B4636',
    muted: '#7A6653',
    accent: '#8B6F3D',
  },
  {
    id: 'corporate',
    label: 'Corporate Red',
    layout: 'corporate',
    gradient: ['#FFFFFF', '#FFFFFF'],
    text: '#DC2626',
    muted: '#1D4ED8',
    accent: '#DC2626',
    blockColor: '#1D4ED8',
    blockText: '#FFFFFF',
  },
];

export const getCardTemplate = (id) => CARD_TEMPLATES.find((t) => t.id === id) || CARD_TEMPLATES[0];
